name: Bug Report
description: Report a bug in Eftdb
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      placeholder: |
        1. Configure entity with ...
        2. Run migration ...
        3. See error ...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: input
    id: dotnet-version
    attributes:
      label: .NET version
      placeholder: "e.g. 10.0.0"
    validations:
      required: false

  - type: input
    id: timescaledb-version
    attributes:
      label: TimescaleDB version
      placeholder: "e.g. 2.17.2"
    validations:
      required: false

  - type: input
    id: eftdb-version
    attributes:
      label: Eftdb version
      placeholder: "e.g. 10.0.0"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or log output relevant to the issue.
    validations:
      required: false
