using CmdScale.EntityFrameworkCore.TimescaleDB.Abstractions;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregate
{
    /// <summary>
    /// Provides a fluent API for configuring a TimescaleDB continuous aggregate using string column references.
    /// Used by code generated by <c>dotnet ef dbcontext scaffold</c> where generic source-entity type parameters
    /// are not available at generation time.
    /// </summary>
    /// <typeparam name="TEntity">The class representing the continuous aggregate view.</typeparam>
    public sealed class ContinuousAggregateStringBuilder<TEntity> where TEntity : class
    {
        private readonly EntityTypeBuilder<TEntity> _builder;

        internal ContinuousAggregateStringBuilder(EntityTypeBuilder<TEntity> builder)
        {
            _builder = builder;
        }

        /// <summary>
        /// Configures whether to create the continuous aggregate with no data initially.
        /// </summary>
        /// <param name="withNoData">True to create with no data; false to populate immediately.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithNoData(bool withNoData = true)
        {
            ContinuousAggregateBuilderCore.WithNoData(_builder, withNoData);
            return this;
        }

        /// <summary>
        /// Configures whether to automatically create indexes on group by columns.
        /// </summary>
        /// <param name="createGroupIndexes">True to create indexes; false otherwise.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> CreateGroupIndexes(bool createGroupIndexes = true)
        {
            ContinuousAggregateBuilderCore.CreateGroupIndexes(_builder, createGroupIndexes);
            return this;
        }

        /// <summary>
        /// Configures whether the continuous aggregate returns only materialized data.
        /// </summary>
        /// <param name="materializedOnly">True to return only materialized data; false to include real-time data.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> MaterializedOnly(bool materializedOnly = true)
        {
            ContinuousAggregateBuilderCore.MaterializedOnly(_builder, materializedOnly);
            return this;
        }

        /// <summary>
        /// Configures the chunk interval for the continuous aggregate's materialized hypertable.
        /// </summary>
        /// <param name="chunkInterval">The chunk interval (e.g., "7 days", "1 month").</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithChunkInterval(string chunkInterval)
        {
            ContinuousAggregateBuilderCore.WithChunkInterval(_builder, chunkInterval);
            return this;
        }

        /// <summary>
        /// Adds an aggregate function mapping using column names as strings.
        /// </summary>
        /// <param name="alias">The output column name on the continuous aggregate view.</param>
        /// <param name="sourceColumn">The source column name from the source hypertable.</param>
        /// <param name="function">The aggregate function to apply.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> AddAggregateFunction(
            string alias, string sourceColumn, EAggregateFunction function)
        {
            ContinuousAggregateBuilderCore.AddAggregateFunction(_builder, alias, sourceColumn, function);
            return this;
        }

        /// <summary>
        /// Adds a GROUP BY column from the source hypertable using its column name as a string.
        /// </summary>
        /// <param name="groupByExpression">The column name or SQL expression to group by.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> AddGroupByColumn(string groupByExpression)
        {
            ContinuousAggregateBuilderCore.AddGroupByColumn(_builder, groupByExpression);
            return this;
        }

        /// <summary>
        /// Adds a WHERE clause to filter data in the continuous aggregate.
        /// </summary>
        /// <param name="whereClause">The SQL WHERE clause expression (without the WHERE keyword).</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> Where(string whereClause)
        {
            ContinuousAggregateBuilderCore.Where(_builder, whereClause);
            return this;
        }
    }
}
