using CmdScale.EntityFrameworkCore.TimescaleDB.Abstractions;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregate
{
    /// <summary>
    /// Provides a fluent API for configuring a TimescaleDB continuous aggregate using string column references.
    /// Used by code generated by <c>dotnet ef dbcontext scaffold</c> where generic source-entity type parameters
    /// are not available at generation time.
    /// </summary>
    /// <typeparam name="TEntity">The class representing the continuous aggregate view.</typeparam>
    public sealed class ContinuousAggregateStringBuilder<TEntity> where TEntity : class
    {
        private readonly EntityTypeBuilder<TEntity> _builder;

        internal EntityTypeBuilder<TEntity> EntityTypeBuilder => _builder;

        internal ContinuousAggregateStringBuilder(EntityTypeBuilder<TEntity> builder)
        {
            _builder = builder;
        }

        /// <summary>
        /// Configures whether to create the continuous aggregate with no data initially.
        /// </summary>
        /// <param name="withNoData">True to create with no data; false to populate immediately.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithNoData(bool withNoData = true)
        {
            ContinuousAggregateBuilderCore.WithNoData(_builder, withNoData);
            return this;
        }

        /// <summary>
        /// Configures whether to automatically create indexes on group by columns.
        /// </summary>
        /// <param name="createGroupIndexes">True to create indexes; false otherwise.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> CreateGroupIndexes(bool createGroupIndexes = true)
        {
            ContinuousAggregateBuilderCore.CreateGroupIndexes(_builder, createGroupIndexes);
            return this;
        }

        /// <summary>
        /// Configures whether the continuous aggregate returns only materialized data.
        /// </summary>
        /// <param name="materializedOnly">True to return only materialized data; false to include real-time data.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> MaterializedOnly(bool materializedOnly = true)
        {
            ContinuousAggregateBuilderCore.MaterializedOnly(_builder, materializedOnly);
            return this;
        }

        /// <summary>
        /// Configures the chunk interval for the continuous aggregate's materialized hypertable.
        /// </summary>
        /// <param name="chunkInterval">The chunk interval (e.g., "7 days", "1 month").</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithChunkInterval(string chunkInterval)
        {
            ContinuousAggregateBuilderCore.WithChunkInterval(_builder, chunkInterval);
            return this;
        }

        /// <summary>
        /// Adds an aggregate function mapping using column names as strings.
        /// </summary>
        /// <param name="alias">The output column name on the continuous aggregate view.</param>
        /// <param name="sourceColumn">The source column name from the source hypertable.</param>
        /// <param name="function">The aggregate function to apply.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> AddAggregateFunction(
            string alias, string sourceColumn, EAggregateFunction function)
        {
            ContinuousAggregateBuilderCore.AddAggregateFunction(_builder, alias, sourceColumn, function);
            return this;
        }

        /// <summary>
        /// Adds a GROUP BY column from the source hypertable using its column name as a string.
        /// </summary>
        /// <param name="groupByExpression">The column name or SQL expression to group by.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> AddGroupByColumn(string groupByExpression)
        {
            ContinuousAggregateBuilderCore.AddGroupByColumn(_builder, groupByExpression);
            return this;
        }

        /// <summary>
        /// Designates the property on the aggregate entity that represents the bucket column.
        /// The view's bucket alias derives from that property's mapped column name, removing the
        /// need to manually call <c>.HasColumnName("time_bucket")</c>.
        /// </summary>
        /// <param name="propertyName">The name of the bucket property on the continuous aggregate.</param>
        /// <returns>The builder for method chaining.</returns>
        /// <exception cref="ArgumentException">Thrown when <paramref name="propertyName"/> is null or whitespace.</exception>
        public ContinuousAggregateStringBuilder<TEntity> WithTimeBucketProperty(string propertyName)
        {
            if (string.IsNullOrWhiteSpace(propertyName))
            {
                throw new ArgumentException("Property name must not be null or whitespace.", nameof(propertyName));
            }

            ContinuousAggregateBuilderCore.WithTimeBucketProperty(_builder, propertyName);
            return this;
        }

        /// <summary>
        /// Adds a WHERE clause to filter data in the continuous aggregate.
        /// </summary>
        /// <param name="whereClause">The SQL WHERE clause expression (without the WHERE keyword).</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> Where(string whereClause)
        {
            ContinuousAggregateBuilderCore.Where(_builder, whereClause);
            return this;
        }

        /// <summary>
        /// Enables or disables columnstore (compression) on the continuous aggregate.
        /// Corresponds to <c>ALTER MATERIALIZED VIEW ... SET (timescaledb.compress = true)</c>.
        /// Enabling compression is a prerequisite for adding a compression policy to a continuous aggregate.
        /// </summary>
        /// <param name="enable">Whether to enable compression. Defaults to <see langword="true"/>.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithCompression(bool enable = true)
        {
            ContinuousAggregateBuilderCore.EnableCompression(_builder, enable);
            return this;
        }

        /// <summary>
        /// Specifies the columns to segment by when compressing the continuous aggregate using column name strings.
        /// Corresponds to <c>timescaledb.compress_segmentby</c>. Implicitly enables compression.
        /// </summary>
        /// <param name="segmentBy">A comma-separated list of column names to segment by.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithCompressionSegmentBy(string segmentBy)
        {
            ContinuousAggregateBuilderCore.WithCompressionSegmentBy(_builder, segmentBy);
            return this;
        }

        /// <summary>
        /// Specifies the order-by clause for compression on the continuous aggregate using a raw SQL string.
        /// Corresponds to <c>timescaledb.compress_orderby</c>. Implicitly enables compression.
        /// </summary>
        /// <param name="orderBy">A comma-separated list of column expressions (e.g., <c>"time DESC, value ASC NULLS LAST"</c>).</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregateStringBuilder<TEntity> WithCompressionOrderBy(string orderBy)
        {
            ContinuousAggregateBuilderCore.WithCompressionOrderBy(_builder, orderBy);
            return this;
        }
    }
}
