using CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregate;

namespace CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregatePolicy
{
    /// <summary>
    /// Extension methods for adding refresh policy configuration to continuous aggregates.
    /// </summary>
    public static class ContinuousAggregateBuilderPolicyExtensions
    {
        /// <summary>
        /// Configures a continuous aggregate refresh policy that automatically refreshes the materialized view on a schedule.
        /// </summary>
        /// <typeparam name="TEntity">The continuous aggregate entity type.</typeparam>
        /// <typeparam name="TSourceEntity">The source hypertable entity type.</typeparam>
        /// <param name="builder">The continuous aggregate builder.</param>
        /// <param name="startOffset">Window start as interval relative to execution time. NULL equals earliest data.</param>
        /// <param name="endOffset">Window end as interval relative to execution time. NULL equals latest data.</param>
        /// <param name="scheduleInterval">Interval between refresh executions. Defaults to "24 hours" if not specified.</param>
        /// <returns>A policy builder for configuring additional refresh policy options.</returns>
        public static ContinuousAggregatePolicyBuilder<TEntity, TSourceEntity> WithRefreshPolicy<TEntity, TSourceEntity>(
            this ContinuousAggregateBuilder<TEntity, TSourceEntity> builder,
            string? startOffset = null,
            string? endOffset = null,
            string? scheduleInterval = null)
            where TEntity : class
            where TSourceEntity : class
        {
            ContinuousAggregatePolicyBuilderCore.WriteRefreshPolicy(
                builder.EntityTypeBuilder,
                startOffset,
                endOffset,
                scheduleInterval);

            return new ContinuousAggregatePolicyBuilder<TEntity, TSourceEntity>(builder);
        }

        /// <summary>
        /// Configures a continuous aggregate refresh policy using string column references.
        /// Used by code generated by <c>dotnet ef dbcontext scaffold</c> where generic source-entity
        /// type parameters are not available at generation time.
        /// </summary>
        /// <typeparam name="TEntity">The continuous aggregate entity type.</typeparam>
        /// <param name="builder">The string-context continuous aggregate builder.</param>
        /// <param name="startOffset">Window start as interval relative to execution time. NULL equals earliest data.</param>
        /// <param name="endOffset">Window end as interval relative to execution time. NULL equals latest data.</param>
        /// <param name="scheduleInterval">Interval between refresh executions. Defaults to "24 hours" if not specified.</param>
        /// <returns>A string-context policy builder for configuring additional refresh policy options.</returns>
        public static ContinuousAggregatePolicyStringBuilder<TEntity> WithRefreshPolicy<TEntity>(
            this ContinuousAggregateStringBuilder<TEntity> builder,
            string? startOffset = null,
            string? endOffset = null,
            string? scheduleInterval = null)
            where TEntity : class
        {
            ContinuousAggregatePolicyBuilderCore.WriteRefreshPolicy(
                builder.EntityTypeBuilder,
                startOffset,
                endOffset,
                scheduleInterval);

            return new ContinuousAggregatePolicyStringBuilder<TEntity>(builder);
        }
    }
}
