using CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregate;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregatePolicy
{
    /// <summary>
    /// Provides a fluent API for configuring a TimescaleDB continuous aggregate refresh policy
    /// using string column references. Used by code generated by <c>dotnet ef dbcontext scaffold</c>
    /// where generic source-entity type parameters are not available at generation time.
    /// </summary>
    /// <typeparam name="TEntity">The class representing the continuous aggregate view.</typeparam>
    public sealed class ContinuousAggregatePolicyStringBuilder<TEntity> where TEntity : class
    {
        private readonly ContinuousAggregateStringBuilder<TEntity> _builder;

        internal EntityTypeBuilder<TEntity> EntityTypeBuilder => _builder.EntityTypeBuilder;

        internal ContinuousAggregatePolicyStringBuilder(ContinuousAggregateStringBuilder<TEntity> builder)
        {
            _builder = builder;
        }

        /// <summary>
        /// Sets the initial start time for the continuous aggregate refresh policy.
        /// </summary>
        /// <param name="initialStart">The first time the policy job is scheduled to run.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregatePolicyStringBuilder<TEntity> WithInitialStart(DateTime initialStart)
        {
            ContinuousAggregatePolicyBuilderCore.WithInitialStart(_builder.EntityTypeBuilder, initialStart);
            return this;
        }

        /// <summary>
        /// Configures whether to issue a notice instead of an error if the policy job already exists.
        /// </summary>
        /// <param name="ifNotExists">True to issue a notice instead of an error if job exists.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregatePolicyStringBuilder<TEntity> WithIfNotExists(bool ifNotExists = true)
        {
            ContinuousAggregatePolicyBuilderCore.WithIfNotExists(_builder.EntityTypeBuilder, ifNotExists);
            return this;
        }

        /// <summary>
        /// Configures whether to override tiered read settings for the continuous aggregate refresh policy.
        /// </summary>
        /// <param name="includeTieredData">True to include tiered data, false to exclude it.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregatePolicyStringBuilder<TEntity> WithIncludeTieredData(bool includeTieredData)
        {
            ContinuousAggregatePolicyBuilderCore.WithIncludeTieredData(_builder.EntityTypeBuilder, includeTieredData);
            return this;
        }

        /// <summary>
        /// Sets the number of buckets processed per batch transaction for the continuous aggregate refresh policy.
        /// </summary>
        /// <param name="bucketsPerBatch">The number of buckets to process per batch. Defaults to 1.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregatePolicyStringBuilder<TEntity> WithBucketsPerBatch(int bucketsPerBatch)
        {
            ContinuousAggregatePolicyBuilderCore.WithBucketsPerBatch(_builder.EntityTypeBuilder, bucketsPerBatch);
            return this;
        }

        /// <summary>
        /// Sets the maximum number of batches per execution for the continuous aggregate refresh policy.
        /// </summary>
        /// <param name="maxBatchesPerExecution">Maximum batches per run. 0 means unlimited. Defaults to 0.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregatePolicyStringBuilder<TEntity> WithMaxBatchesPerExecution(int maxBatchesPerExecution)
        {
            ContinuousAggregatePolicyBuilderCore.WithMaxBatchesPerExecution(_builder.EntityTypeBuilder, maxBatchesPerExecution);
            return this;
        }

        /// <summary>
        /// Sets the direction of incremental refresh for the continuous aggregate refresh policy.
        /// </summary>
        /// <param name="refreshNewestFirst">True to refresh newest data first, false to refresh oldest first. Defaults to true.</param>
        /// <returns>The builder for method chaining.</returns>
        public ContinuousAggregatePolicyStringBuilder<TEntity> WithRefreshNewestFirst(bool refreshNewestFirst = true)
        {
            ContinuousAggregatePolicyBuilderCore.WithRefreshNewestFirst(_builder.EntityTypeBuilder, refreshNewestFirst);
            return this;
        }
    }
}
