using CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregate;
using CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.ContinuousAggregatePolicy;
using CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.RetentionPolicy;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace CmdScale.EntityFrameworkCore.TimescaleDB.Configuration.CompressionPolicy
{
    /// <summary>
    /// Provides extension methods for configuring TimescaleDB compression policies using the EF Core Fluent API.
    /// </summary>
    public static class CompressionPolicyTypeBuilder
    {
        /// <summary>
        /// Configures a TimescaleDB compression policy for the entity.
        /// Exactly one of <paramref name="after"/> or <paramref name="createdBefore"/> must be specified.
        /// </summary>
        /// <remarks>
        /// The policy schedules automatic conversion of chunks to the columnstore (compression) via
        /// <c>add_compression_policy()</c>. The target table must already have compression enabled
        /// (see <c>.IsHypertable().WithCompression()</c> or the <c>EnableCompression</c> hypertable option).
        /// All interval values are strings (e.g., "7 days"). No <see cref="TimeSpan"/> overloads are provided
        /// because the underlying unit depends on the time-column type.
        /// </remarks>
        /// <example>
        /// <code>
        /// modelBuilder.Entity&lt;Reading&gt;()
        ///     .WithCompressionPolicy(after: "7 days", scheduleInterval: "1 day");
        /// </code>
        /// </example>
        /// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
        /// <param name="entityTypeBuilder">The builder for the entity type being configured.</param>
        /// <param name="after">The interval after which chunks are compressed. Mutually exclusive with <paramref name="createdBefore"/>.</param>
        /// <param name="createdBefore">The interval relative to chunk creation time. Mutually exclusive with <paramref name="after"/>.</param>
        /// <param name="scheduleInterval">The interval between policy job executions.</param>
        /// <param name="initialStart">The first time the policy job is scheduled to run. When null the scheduler derives the initial run from the schedule interval.</param>
        /// <param name="timezone">The PostgreSQL time zone used when computing the initial start time.</param>
        /// <param name="ifNotExists">When <see langword="true"/>, no error is raised if the policy already exists.</param>
        /// <returns>The same builder instance so that multiple calls can be chained.</returns>
        public static EntityTypeBuilder<TEntity> WithCompressionPolicy<TEntity>(
            this EntityTypeBuilder<TEntity> entityTypeBuilder,
            string? after = null,
            string? createdBefore = null,
            string? scheduleInterval = null,
            DateTime? initialStart = null,
            string? timezone = null,
            bool? ifNotExists = null) where TEntity : class
        {
            WriteCompressionPolicy(entityTypeBuilder, after, createdBefore, scheduleInterval, timezone, ifNotExists);

            if (initialStart.HasValue)
                PolicyJobBuilderCore.WithInitialStart(entityTypeBuilder, CompressionPolicyAnnotations.InitialStart, initialStart.Value);

            return entityTypeBuilder;
        }

        /// <summary>
        /// Configures a TimescaleDB compression policy for the entity.
        /// Used by code generated by <c>dotnet ef dbcontext scaffold</c>.
        /// Exactly one of <paramref name="after"/> or <paramref name="createdBefore"/> must be specified.
        /// </summary>
        /// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
        /// <param name="entityTypeBuilder">The builder for the entity type being configured.</param>
        /// <param name="after">The interval after which chunks are compressed. Mutually exclusive with <paramref name="createdBefore"/>.</param>
        /// <param name="createdBefore">The interval relative to chunk creation time. Mutually exclusive with <paramref name="after"/>.</param>
        /// <param name="scheduleInterval">The interval between policy job executions.</param>
        /// <param name="timezone">The PostgreSQL time zone used when computing the initial start time.</param>
        /// <param name="ifNotExists">When <see langword="true"/>, no error is raised if the policy already exists.</param>
        /// <returns>A builder for chaining optional parameters not representable as literal constructor arguments.</returns>
        public static CompressionPolicyStringBuilder<TEntity> WithCompressionPolicy<TEntity>(
            this EntityTypeBuilder<TEntity> entityTypeBuilder,
            string? after,
            string? createdBefore,
            string? scheduleInterval,
            string? timezone,
            bool? ifNotExists) where TEntity : class
        {
            WriteCompressionPolicy(entityTypeBuilder, after, createdBefore, scheduleInterval, timezone, ifNotExists);
            return new CompressionPolicyStringBuilder<TEntity>(entityTypeBuilder);
        }

        /// <summary>
        /// Configures a TimescaleDB compression policy for a hypertable that already has a retention policy
        /// configured, chained after the retention policy configuration.
        /// Used by code generated by <c>dotnet ef dbcontext scaffold</c>.
        /// Exactly one of <paramref name="after"/> or <paramref name="createdBefore"/> must be specified.
        /// </summary>
        /// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
        /// <param name="builder">The retention policy builder being configured.</param>
        /// <param name="after">The interval after which chunks are compressed. Mutually exclusive with <paramref name="createdBefore"/>.</param>
        /// <param name="createdBefore">The interval relative to chunk creation time. Mutually exclusive with <paramref name="after"/>.</param>
        /// <param name="scheduleInterval">The interval between policy job executions.</param>
        /// <param name="timezone">The PostgreSQL time zone used when computing the initial start time.</param>
        /// <param name="ifNotExists">When <see langword="true"/>, no error is raised if the policy already exists.</param>
        /// <returns>A builder for chaining optional parameters not representable as literal constructor arguments.</returns>
        public static CompressionPolicyStringBuilder<TEntity> WithCompressionPolicy<TEntity>(
            this RetentionPolicyStringBuilder<TEntity> builder,
            string? after,
            string? createdBefore,
            string? scheduleInterval,
            string? timezone,
            bool? ifNotExists) where TEntity : class
        {
            WriteCompressionPolicy(builder.EntityTypeBuilder, after, createdBefore, scheduleInterval, timezone, ifNotExists);
            return new CompressionPolicyStringBuilder<TEntity>(builder.EntityTypeBuilder);
        }

        /// <summary>
        /// Configures a TimescaleDB compression policy for a continuous aggregate, chained directly
        /// after the <see cref="ContinuousAggregateStringBuilder{TEntity}"/> configuration.
        /// Exactly one of <paramref name="after"/> or <paramref name="createdBefore"/> must be specified.
        /// </summary>
        /// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
        /// <param name="builder">The continuous aggregate builder being configured.</param>
        /// <param name="after">The interval after which chunks are compressed. Mutually exclusive with <paramref name="createdBefore"/>.</param>
        /// <param name="createdBefore">The interval relative to chunk creation time. Mutually exclusive with <paramref name="after"/>.</param>
        /// <param name="scheduleInterval">The interval between policy job executions.</param>
        /// <param name="timezone">The PostgreSQL time zone used when computing the initial start time.</param>
        /// <param name="ifNotExists">When <see langword="true"/>, no error is raised if the policy already exists.</param>
        /// <returns>A builder for chaining optional parameters not representable as literal constructor arguments.</returns>
        public static CompressionPolicyStringBuilder<TEntity> WithCompressionPolicy<TEntity>(
            this ContinuousAggregateStringBuilder<TEntity> builder,
            string? after,
            string? createdBefore,
            string? scheduleInterval,
            string? timezone,
            bool? ifNotExists) where TEntity : class
        {
            WriteCompressionPolicy(builder.EntityTypeBuilder, after, createdBefore, scheduleInterval, timezone, ifNotExists);
            return new CompressionPolicyStringBuilder<TEntity>(builder.EntityTypeBuilder);
        }

        /// <summary>
        /// Configures a TimescaleDB compression policy for a continuous aggregate that already has a
        /// refresh policy configured, chained after the refresh policy configuration.
        /// Exactly one of <paramref name="after"/> or <paramref name="createdBefore"/> must be specified.
        /// </summary>
        /// <typeparam name="TEntity">The type of the entity being configured.</typeparam>
        /// <param name="builder">The continuous aggregate policy builder being configured.</param>
        /// <param name="after">The interval after which chunks are compressed. Mutually exclusive with <paramref name="createdBefore"/>.</param>
        /// <param name="createdBefore">The interval relative to chunk creation time. Mutually exclusive with <paramref name="after"/>.</param>
        /// <param name="scheduleInterval">The interval between policy job executions.</param>
        /// <param name="timezone">The PostgreSQL time zone used when computing the initial start time.</param>
        /// <param name="ifNotExists">When <see langword="true"/>, no error is raised if the policy already exists.</param>
        /// <returns>A builder for chaining optional parameters not representable as literal constructor arguments.</returns>
        public static CompressionPolicyStringBuilder<TEntity> WithCompressionPolicy<TEntity>(
            this ContinuousAggregatePolicyStringBuilder<TEntity> builder,
            string? after,
            string? createdBefore,
            string? scheduleInterval,
            string? timezone,
            bool? ifNotExists) where TEntity : class
        {
            WriteCompressionPolicy(builder.EntityTypeBuilder, after, createdBefore, scheduleInterval, timezone, ifNotExists);
            return new CompressionPolicyStringBuilder<TEntity>(builder.EntityTypeBuilder);
        }

        private static void WriteCompressionPolicy(
            EntityTypeBuilder entityTypeBuilder,
            string? after,
            string? createdBefore,
            string? scheduleInterval,
            string? timezone,
            bool? ifNotExists)
        {
            bool hasAfter = !string.IsNullOrWhiteSpace(after);
            bool hasCreatedBefore = !string.IsNullOrWhiteSpace(createdBefore);

            ConventionValidationHelper.ValidateExclusiveFields("WithCompressionPolicy", "after", hasAfter, "createdBefore", hasCreatedBefore);

            entityTypeBuilder.HasAnnotation(CompressionPolicyAnnotations.HasCompressionPolicy, true);

            if (hasAfter)
                entityTypeBuilder.HasAnnotation(CompressionPolicyAnnotations.After, after!);

            if (hasCreatedBefore)
                entityTypeBuilder.HasAnnotation(CompressionPolicyAnnotations.CreatedBefore, createdBefore!);

            if (!string.IsNullOrWhiteSpace(scheduleInterval))
                entityTypeBuilder.HasAnnotation(CompressionPolicyAnnotations.ScheduleInterval, scheduleInterval);

            if (!string.IsNullOrWhiteSpace(timezone))
                entityTypeBuilder.HasAnnotation(CompressionPolicyAnnotations.Timezone, timezone);

            if (ifNotExists.HasValue)
                entityTypeBuilder.HasAnnotation(CompressionPolicyAnnotations.IfNotExists, ifNotExists.Value);
        }
    }
}
